name: Test
on: [push]

jobs:
  e2e:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip uv
          uv sync --dev
          uv pip install -e .
      - name: Test with pytest
        run: |
          PYTHONPATH=src uv run pytest -n auto --cov=src --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov-report term --cov-report xml
      - name: Upload pytest test results
        uses: actions/upload-artifact@v4
        with:
          name: pytest-results--${{ matrix.python-version }}
          path: junit/test-results-${{ matrix.python-version }}.xml
        if: ${{ always() }}
